/**
 * @file app/api/v1/postProjects/schema.ts
 *
 * Manual runtime validation for the POST /api/v1/postProjects request body.
 * No external libraries — plain TypeScript + utility types derived from the
 * existing Prisma types in lib/types.ts.
 *
 * orbit and visual are NOT part of the client input — they are auto-generated
 * by the service layer based on the project's `order` slot.
 *
 * ─── Returns ──────────────────────────────────────────────────────────────────
 *   { ok: true,  data: ValidatedProjectInput }
 *   { ok: false, field: string, message: string }
 */

import type { Project } from '@/lib/types'

// ─── Derived input shape ──────────────────────────────────────────────────────

/**
 * Fully-validated project input, ready to pass to the service layer.
 * Derived from the Prisma `Project` type so field names always stay in sync.
 *
 *  • id, createdAt, updatedAt — omitted (auto-generated by DB)
 *  • orbit, visual            — omitted (auto-generated by the service)
 *  • active                   — optional; service always forces it to false
 */
export type ValidatedProjectInput =
  Omit<Project, 'id' | 'createdAt' | 'updatedAt' | 'orbit' | 'visual' | 'active'> & {
    active?: boolean
  }

/**
 * Raw HTTP body shape — identical to ValidatedProjectInput except
 * `date` is still a string (not yet coerced to Date).
 */
type RawProjectInput = Omit<ValidatedProjectInput, 'date'> & { date: string }

// ─── Validation result ────────────────────────────────────────────────────────

type ValidationOk   = { ok: true;  data: ValidatedProjectInput }
type ValidationFail = { ok: false; field: string; message: string }
export type ValidationResult = ValidationOk | ValidationFail

// ─── Helpers ──────────────────────────────────────────────────────────────────

const isNonEmptyString = (v: unknown): v is string =>
  typeof v === 'string' && v.trim().length > 0

const isValidUrl = (v: unknown): boolean => {
  if (typeof v !== 'string') return false
  try {
    const url = new URL(v)
    return url.protocol === 'https:' || url.protocol === 'http:'
  } catch {
    return false
  }
}

// ─── Main validator ───────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function validatePostProject(body: any): ValidationResult {

  // ── Required string fields ───────────────────────────────────────────────────
  const requiredStrings: Array<keyof RawProjectInput> = [
    'slug', 'title', 'category', 'date', 'shortDesc', 'fullDesc',
  ]
  for (const key of requiredStrings) {
    if (!isNonEmptyString(body[key])) {
      return { ok: false, field: key, message: `"${key}" is required and must be a non-empty string` }
    }
  }

  // ── Slug: lowercase alphanumeric + hyphens, max 80 chars ────────────────────
  if (!/^[a-z0-9-]+$/.test(body.slug)) {
    return {
      ok: false,
      field: 'slug',
      message: 'slug must only contain lowercase letters, numbers, and hyphens (e.g. "my-cool-project")',
    }
  }
  if (body.slug.length > 80) {
    return { ok: false, field: 'slug', message: 'slug must be 80 characters or fewer' }
  }

  // ── Date: coerce ISO string → Date ──────────────────────────────────────────
  const parsedDate = new Date(body.date)
  if (isNaN(parsedDate.getTime())) {
    return { ok: false, field: 'date', message: '"date" must be a valid ISO 8601 date string' }
  }

  // ── Tags: non-empty string array, max 10 items ───────────────────────────────
  if (!Array.isArray(body.tags) || body.tags.length === 0) {
    return { ok: false, field: 'tags', message: '"tags" must be a non-empty array of strings' }
  }
  if (body.tags.length > 10) {
    return { ok: false, field: 'tags', message: '"tags" must contain 10 or fewer items' }
  }
  for (const tag of body.tags) {
    if (!isNonEmptyString(tag)) {
      return { ok: false, field: 'tags', message: 'Every item in "tags" must be a non-empty string' }
    }
  }

  // ── Order: positive integer (determines orbit slot) ──────────────────────────
  if (typeof body.order !== 'number' || !Number.isInteger(body.order) || body.order < 1) {
    return { ok: false, field: 'order', message: '"order" must be a positive integer (≥ 1)' }
  }

  // ── Optional URLs ────────────────────────────────────────────────────────────
  if (body.githubURL != null && !isValidUrl(body.githubURL)) {
    return { ok: false, field: 'githubURL', message: '"githubURL" must be a valid URL or null' }
  }
  if (body.deployedURL != null && !isValidUrl(body.deployedURL)) {
    return { ok: false, field: 'deployedURL', message: '"deployedURL" must be a valid URL or null' }
  }

  // ── Return clean, coerced data ───────────────────────────────────────────────
  return {
    ok: true,
    data: {
      slug:        body.slug.trim(),
      title:       body.title.trim(),
      category:    body.category.trim(),
      date:        parsedDate,
      shortDesc:   body.shortDesc.trim(),
      fullDesc:    body.fullDesc.trim(),
      // deduplicate + trim tags
      tags:        [...new Set<string>((body.tags as string[]).map((t: string) => t.trim()))],
      order:       body.order,
      githubURL:   body.githubURL   ?? null,
      deployedURL: body.deployedURL ?? null,
    },
  }
}